import React, { useState, useEffect } from 'react';
import Navbar from '../components/Navbar';
import { useNavigate } from 'react-router-dom';
import { FileText, Copy, Download, AlertTriangle, CheckCircle } from 'lucide-react';

export default function ReportPreview({ user }) {
  const [report, setReport] = useState(null);
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const latest = JSON.parse(localStorage.getItem('proofshield_latest_case'));
    if (latest) {
      setReport(latest);
    }
  }, []);

  const handleCopy = () => {
    if (!report) return;
    const text = generateTextReport();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!report) return;
    const text = generateTextReport();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ProofShield_Incident_Report_${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateTextReport = () => {
    return `INCIDENT REPORT - PROOFSHIELD AI
Date Generated: ${new Date().toLocaleString()}
Harm Type: ${report.harm_type}
Risk Level: ${report.risk_level}

SUMMARY:
${report.report_summary}

IDENTIFIED RED FLAGS:
${report.red_flags.map(f => `- ${f}`).join('\n')}

EVIDENCE REQUIRED:
${report.evidence_checklist.map(e => `- [ ] ${e}`).join('\n')}

IMMEDIATE STEPS TAKEN/ADVISED:
${report.immediate_steps.map(s => `- ${s}`).join('\n')}

---
Generated by ProofShield AI Autonomous Crisis Agent.`;
  };

  return (
    <div className="min-h-screen flex flex-col p-4 md:p-8">
      <Navbar user={user} />
      
      <div className="flex-1 max-w-4xl mx-auto w-full">
        <div className="mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold flex items-center gap-3">
              <FileText className="text-primary" /> Report Preview
            </h1>
            <p className="text-gray-400 mt-2">Formal complaint package generated by your latest AI session.</p>
          </div>
          {report && (
            <div className="flex gap-3">
              <button onClick={handleCopy} className="btn-secondary text-sm !px-4 !py-2">
                {copied ? <CheckCircle className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
              <button onClick={handleDownload} className="btn-primary text-sm !px-4 !py-2">
                <Download className="w-4 h-4" /> Download .txt
              </button>
            </div>
          )}
        </div>

        {!report ? (
          <div className="glass-panel p-12 text-center flex flex-col items-center">
            <FileText className="w-16 h-16 text-gray-500 mb-4" />
            <h2 className="text-xl font-semibold mb-2">No Report Found</h2>
            <p className="text-gray-400 mb-6">Run an analysis in the Dashboard to generate an automated report.</p>
            <button onClick={() => navigate('/dashboard')} className="btn-primary">
              Go to Dashboard
            </button>
          </div>
        ) : (
          <div className="glass-panel p-8 bg-white/5 font-mono text-sm leading-relaxed text-gray-300 shadow-2xl relative overflow-hidden">
            {/* Watermark */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-[150px] font-black text-white/5 rotate-[-45deg] pointer-events-none">
              PROOFSHIELD
            </div>
            
            <div className="relative z-10">
              <h2 className="text-2xl font-bold text-white mb-6 border-b border-white/10 pb-4">INCIDENT REPORT PACKAGE</h2>
              
              <div className="grid grid-cols-2 gap-4 mb-6">
                <div>
                  <span className="text-gray-500 uppercase tracking-widest text-xs block mb-1">Date Generated</span>
                  <span className="text-white">{new Date().toLocaleString()}</span>
                </div>
                <div>
                  <span className="text-gray-500 uppercase tracking-widest text-xs block mb-1">Risk Assessment</span>
                  <span className="text-red-400 font-bold">{report.risk_level} RISK - {report.harm_type}</span>
                </div>
              </div>

              <div className="mb-6">
                <span className="text-gray-500 uppercase tracking-widest text-xs block mb-2">Executive Summary</span>
                <p className="bg-black/30 p-4 rounded-lg border border-white/5">{report.report_summary}</p>
              </div>

              <div className="mb-6">
                <span className="text-gray-500 uppercase tracking-widest text-xs block mb-2">Identified Threat Vectors</span>
                <ul className="list-disc pl-5 space-y-1">
                  {report.red_flags.map((flag, idx) => (
                    <li key={idx} className="text-orange-300">{flag}</li>
                  ))}
                </ul>
              </div>

              <div className="mb-6">
                <span className="text-gray-500 uppercase tracking-widest text-xs block mb-2">Required Evidence Log</span>
                <ul className="space-y-2">
                  {report.evidence_checklist.map((item, idx) => (
                    <li key={idx} className="flex items-center gap-2">
                      <div className="w-3 h-3 border border-gray-400 rounded-sm"></div>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
